{
 "title": "test1",
 "time": { "from": "2022-08-30T20:24:44.216Z", "to": "2022-08-31T07:24:55.509Z" },
 "templating": {
  "list": [
   {
    "name": "model_id",
    "query": "SELECT DISTINCT model_id FROM analyzer_positions ORDER BY model_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Returns (cumprod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  EXP(sum(LN(1 + ret)) OVER (PARTITION BY model_id\n                         ORDER BY timestamp)) AS cum_ret,\n  \"model_id\"\nFROM analyzer_rets\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(abs(\"position_diff\")) OVER (PARTITION BY model_id\n                         ORDER BY timestamp) AS cum_vol,\n  \"model_id\"\nFROM analyzer_positions\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Model Positions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"position\",\n  \"symbol\"\nFROM analyzer_positions\nWHERE\n  model_id = '$model_id' AND\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Model Volumes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(abs(\"position_diff\")) OVER (PARTITION BY symbol\n                         ORDER BY timestamp) AS cum_vol,\n  \"symbol\"\nFROM analyzer_positions\nWHERE\n  model_id = '$model_id' AND\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Model raw positions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"positions\"\nFROM positions\nWHERE\n  model_id = '$model_id'\nORDER BY 1"
    }
   ]
  }
 ]
}